
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module reaction25(


	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


// Notes about HEX displays -- these are logic low.
// setup things that are true in all states
// HEX3 - HEX5 should be blank
assign HEX3 = 8'b01000000;            
assign HEX4 = 8'b11111111;
assign HEX5 = 8'b11111111;

// set 0.

// need variables
reg [1:0] state_reg;
wire OnOff = SW[0];
wire R = ~KEY[1]; // this links to push button detection Key1 on board
wire clk = MAX10_CLK1_50;

wire clk100Hz;
wire [9:0] Digit3, Digit2, Digit1, Digit0; // there were a few typos here in class on 11/4
wire [9:0] ledn; // there were a few typos here in class on 11/4 -- needs to make what is instantiated
wire myFLAG;

// state machine parameters
parameter idle = 2'b00;
parameter delay = 2'b01;
parameter timing = 2'b10;
parameter display = 2'b11;

initial begin
	state_reg = idle;
end

//=======================================================
//  Finite State Machine
//=======================================================

always @(posedge clk100Hz) // consider changing to slower clock
   begin
	
		case(state_reg)
			idle:  if (OnOff & !R) 	state_reg <= delay;
					 else 				state_reg <= idle;
			
			delay: if (OnOff & myFLAG & !R)	state_reg <= timing;
					 else					state_reg <= delay;
			
			timing:if (OnOff & R)   state_reg <= display;
					 else					state_reg <= timing;
			
			display:if (!OnOff)		state_reg <= idle;
					  else				state_reg <= display;
			
			default:						state_reg <= idle;
		endcase
	
	end


	
	
	

// Instantiated Slow Clock
ClockDivider100 CLK_MUT(clk, clk100Hz);



reaction2 React_MUT(clk100Hz, state_reg, myFLAG, ledn, Digit1, Digit0, Digit2);


//---------------------------------------------------------------------
//THIS CODE WAS ADDED AFTER CLASS
// HARDWARE UPDATE CODE
//---------------------------------------------------------------------
assign LEDR = ledn;
assign HEX0[7] = 1;
assign HEX0[6:0] = ~Digit0; 
assign HEX1[7] = 1;
assign HEX1[6:0] = ~Digit1;
assign HEX2[7] = 1;
assign HEX2[6:0] = ~Digit2;



endmodule